### ISSUE TITLE
Int64 vs Int32 issue

### ISSUE THREAD

**Issue by fabiencomte** [OctopusDeploy/Halibut#1]
Hello,
First of all, great job that you did :-)

I'm building and running all on the same 32 bits computer.

I have a service with this function
int Ping(int a);

I have this exception:
Server exception: 
System.Reflection.AmbiguousMatchException: Could not decide which candidate to call out of the following methods:
 - Int32 Ping(Int32)
The request arguments were:
Int64

   à Halibut.ServiceModel.ServiceInvoker.SelectMethod(IList`1 methods, RequestMessage requestMessage) dans y:\work\f70967c2fadadfb5\source\Halibut\ServiceModel\ServiceInvoker.cs:ligne 100
   à Halibut.ServiceModel.ServiceInvoker.Invoke(RequestMessage requestMessage) dans y:\work\f70967c2fadadfb5\source\Halibut\ServiceModel\ServiceInvoker.cs:ligne 29
   à Halibut.HalibutRuntime.HandleIncomingRequest(RequestMessage request) dans y:\work\f70967c2fadadfb5\source\Halibut\HalibutRuntime.cs:ligne 125
   à Halibut.Transport.Protocol.MessageExchangeProtocol.InvokeAndWrapAnyExceptions(RequestMessage request, Func`2 incomingRequestProcessor) dans y:\work\f70967c2fadadfb5\source\Halibut\Transport\Protocol\MessageExchangeProtocol.cs:ligne 139
0 logs remaining

i tried with that but result is the same.
Int32 Ping(Int32 a);

Do you have any idea ?

Thank you

**Comment by PaulStovell** [comment]
What if you change the method to take int64?

**Comment by PaulStovell** [comment]
Just checked - using int64/long will work. Int32 limitation is due to Json.net

**Comment by fabiencomte** [comment]
It works, thank you.

**Comment by janpieterz** [comment]
@PaulStovell would there be any way of making this work without going to 64int? I'm currently sending a 'raw' string that I then cast upon retrieval, since I don't want to risk having a 64 bit int on a 32 bit machine. Would be more than happy to take the work on.

**Comment by mattgwagner** [comment]
I ran into this while producing a spike utilizing the library, didn't know what was going on until I came across this closed ticket. The diagram in the README include integers in the interface definition, which also threw me off.
