### ISSUE TITLE
Listening more than once to the same port throws an exception

### ISSUE THREAD

**Issue by janpieterz** [OctopusDeploy/Halibut#19]
In my app I dynamically have a couple of tentacles, who have a port connected and can be either polling or pushing.
I expected the listen call to check if it is already listening, if not to start listening. What it actually does is it created a SecureListener regardless and starts it. 

I'd propose a check to see if we're already listening on that endpoint. If not, we add a listener, if so we return the port directly.

Let me know if you guys would appreciate this or if I need to keep an extra state in my own app to make sure I don't do a double-listen.

**Comment by droyad** [comment]
Hi @janpieterz, we've neglected this for over a year, sorry. 

I would expect calling listen twice on the same port to throw an exception, just as if another app was already listening. So adding code to silently handle that case may cause callers to have the wrong expectation. Better to handle duplicate ports in the calling code.

Thank you for the offer though.

**Comment by vincentparrett** [comment]
I just hit this issue today, different parts (and threads) of my server code attempt to call the "tentacle" which is in polling mode, sometimes it works, sometimes not, depending on whether those calls overlap. @janpieterz suggestion is a good one.. but I wonder if a single secureclient can handle multiple calls at the same time (I haven't dug into it yet).

**Comment by droyad** [comment]
In Octopus we use a single secure client for all polling tentacles. If for some reason you don't want to keep the listening port open of the life of the application, you should build a wrapper that keeps track of how many things are using it and open/close it appropriately.

**Comment by vincentparrett** [comment]
That makes sense. I did already create a wrapper, but will have to rethink it to enable polling.
