### ISSUE TITLE
ClientCertificateValidator sample not fits with actual lib

### ISSUE THREAD

**Issue by fabiencomte** [OctopusDeploy/Halibut#2]
Hello,
This article show how to use a custom ClientCertificateValidator but it looks not compatible with actual Library. Do you have a new sample please ?
http://www.codeproject.com/Articles/554692/Halibut-a-secure-communication-stack-for-NET-Mono

**Comment by fabiencomte** [comment]
Is that possible to allow not just one trusted but a list of trusted on both sides ?

Thank you.

**Comment by fabiencomte** [comment]
I found for client, Trust add to a list. Is that possible to use a list for createclient ?

**Comment by PaulStovell** [comment]
It isn't possible but if you want to send a pull request I can consider it

**Comment by fabiencomte** [comment]
Ok I will try.
