### ISSUE TITLE
Make RetryCountLimit static instead of const

### ISSUE THREAD

**Issue by janpieterz** [OctopusDeploy/Halibut#37]
I'm currently using the timers to manage the retries. In the setup I use it, the retries are managed out of Halibut already. It would be nice to set the RetryCountLimit as with the other items in `HalibutLimits`.

More than happy to make a pull request for this! 
If so, let me know if you'd like to relocate this one HalibutLimits too, or keep it in the clients (or make to different ones for each in HalibutLimits).

**Comment by droyad** [comment]
Sorry about the delay in responding, so I've done the PR for this.

**Comment by janpieterz** [comment]
Great stuff, thanks a lot @droyad !
