### ISSUE TITLE
File transfer using Halibut?

### ISSUE THREAD

**Issue by nkwinder** [OctopusDeploy/Halibut#38]
Hello, this is a question rather than a problem / issue, but i didn't know where else to ask.

I think that halibut can be used to transfer files, is this correct? 
I read in doc: "Requests and responses can also contain streams of arbitrary length".
Is there any code sample on how to transfer a file (with progress report)? 
Is there any doc on how octopus actually transfers packages? (I know about octodiff, but i think this is just for patch generation without containing any file-transfer logic, right?).

thanks in advance

**Comment by droyad** [comment]
Hi @nkwinder, I'm not fully across how this works, but I think you create a `DataStream`, for example using the `DataSteam.FromStream` method (https://github.com/OctopusDeploy/Halibut/blob/97482950e4ec40526bb0bc2a88d0d5a63631954a/source/Halibut/DataStream.cs#L96) that takes a func to update the progress.

You then either pass the `DataSteam` object in the proxied method call (eg `UploadResult UploadFile(string fileName, DataStream package);` or put it as a property on a type on a proxied method call (eg `ScriptResult ExecuteCommand(StartScriptCommand command);` where `StartScriptCommand` contains a property `List<DataFile> AdditionalFiles`

Hope that helps

**Comment by droyad** [comment]
Oh, also checkout this test https://github.com/OctopusDeploy/Halibut/blob/848fa5d6a4a28d07985cf71f72aa87c5d3ded78c/source/Halibut.Tests/UsageFixture.cs#L118

**Comment by nkwinder** [comment]
Thanks for the quick reply! I'll try, but can't say it's entirely clear to me. I'll have a go.
