### ISSUE TITLE
Client with server samples issue with mono

### ISSUE THREAD

**Issue by fabiencomte** [OctopusDeploy/Halibut#4]
if i start samples with mono :
mono.exe Halibut.SampleServer.exe
then
mono.exe Halibut.SampleClient.exe
I get this exception on client side
Unhandled Exception:
Halibut.HalibutClientException: An error occurred when sending a request to 'https://localhost:8433/', after the request began: CreateZStream

**Comment by PaulStovell** [comment]
Mono compatibility was important for the first version of Halibut, but it's not something we've tried to make work for this latest version. If you happen to find a fix I'll be happy to take a PR!

**Comment by fabiencomte** [comment]
I found a dirty fix bypassing compression in MessageExchangeStream.cs but I'm not enough expert with streams to say why.

T ReadBsonMessage<T>()
        {
            using (var bson = new BsonReader(stream) { CloseInput = false })
            {
                return (T)serializer.Deserialize<MessageEnvelope>(bson).Message;
            }            
        }

and

   void WriteBsonMessage<T>(T messages)
        {
            using (var bson = new BsonWriter(stream) { CloseOutput = false })
            {
                serializer.Serialize(bson, new MessageEnvelope { Message = messages });
                bson.Flush();
            }
        }
