### ISSUE TITLE
Connection fails only to specific listening servers after period of activity

### ISSUE THREAD

**Issue by janpieterz** [OctopusDeploy/Halibut#41]
I've been trying to tackle an issue for about two months now. 
I'm not sure if this would be a Halibut issue, or just Windows, or something different, but am hoping this sounds familiar to you or you'd be able to point out ways to debug this better.

We've got Halibut setup in listening mode on quite a couple of machines. This used to work perfectly fine, until an ISP in between us and some machines was changed. Since then (exactly on that date), we started seeing a weird saturation-like issue, where the sites where the ISP has changed suddenly start disconnecting after a certain time period.

Interestingly, restarting the applications on both ends does _not_ resolve this issue **but** even more interesting, restarting our server (aka the Halibut Client connecting to the listening Halibut Servers) does resolve the issue. Though this issue only occurs on those machines that are behind the ISP change, restarting those does not affect anything but restarting our server does resolve the issue, no other change needed.

Things that I've seen, that might or might not be related:

- Executing a 'health/are-you-up' call seems to make this occur less often, though it does not eliminate
- On the Halibut Server side, behind the ISP, netstat _sometimes_ shows ~5 Established connections to our client (our serverse) while those show 1. Sometimes it shows 0 on each side but a connection still will timeout/fail when trying.
- We run in Microsoft Azure but have set the TCP squeezing to 30 minutes, while the health calls execute once a minute.
- It does often (not sure if always) try to EstablishNewConnection within the SecureClient, and either fail at `ConnectWithTimeout` but most often at `System.Net.Security.SslState.EndProcessAuthentication` with a timeout
- Stopping our halibut client (our servers) does _not_ immediately remove Established connections on halibut server. Waiting for a certain period (5-15 minutes) does stop them. Starting the halibut client again after all are closed has no effect (still fails)
- When starting up again (halibut client) the connection shows as Established on both ends, until it fails the `System.Net.Security.SslState.EndProcessAuthentication`. It then keeps the connection open on the halibut server but the client (our server) does not have the connection anymore. This essentially repeats for each connection attempt and presumably causes more connections to open up to the client.
- It occurs about one time a day, sometimes a bit more, sometimes a bit less. 
- We run the connections to the listeners over two machines on our end and it does not happen at both at the same time

I know this is super vague, I've been breaking my head over it for quite some time. The restart of our server solving it is the most annoying bit, as netstat does not show any indication anything still being open, our services on both ends stopped not having any effect. I've been unable to replicate this locally, it's only on those sites. The ISP has been extremely unhelpful in even giving access to the routers (I was thinking it could possibly be some kind of protection setup in the router that kicks in, looking to turn it off). Any ideas to debug, suggestions in any way, would be much appreciated.

**Comment by vanessalove** [comment]
Hi @janpieterz - The way we would suggest troubleshooting this to start would be to use our Tentacle Ping/Pong https://github.com/OctopusDeploy/TentaclePing 

Running the ping from the server, and pong from the client you can attempt to trace any network outtages. It's a tool we recommend for Octopus users and Tentacle, but it works off Halibut. 

You could also run this between a client that has been stable to compare differences.
We would then determine an Octopus problem versus a network problem. Mostly it should give you a smaller range of figuring out the potential issues.

**Comment by janpieterz** [comment]
Hi @vanessalove  - great suggestion, thanks, I'll be digging into it.

**Comment by droyad** [comment]
@janpieterz A few things come to mind:
- Could you be running out of source ports? It doesn't sound like it though.
- Is Windows limiting the number of connections to the same host? Are these running on a server OS?
- What options are you passing to netstat?
- Have you tried taking a dump of the processes and looked for hanging threads/connections?

It does sound like a problem in the middle. Perhaps there is a proxy or firewall that is keeping those connections open and not allowing new ones. Try logging the failures as well as response times, in one instance I found that connections were lagging and then failing every hour... turns out another customer was hammering the shared firewall with requests until it rebooted.

There are a few sample test projects in the Halibut source that may help you create a small app to attempt to diagnose.

**Comment by janpieterz** [comment]
@droyad  thanks for your response!

The source ports seem to be fine, we have plenty available and new (other) connections get made without issue.
I'm not sure how to find out if Windows is limiting the number of connections? It'd be a reasonable scenario, unless it'd need to be in the netstat for that. I've also looked into .NET possible having limits/possibility for hanging fruit.

The netstat command run is `netstat -ano | find "11337"` to find the ones with the port used in it.
Have not tried a process dump yet, though the netstat seems to suggest there are no connections it wouldn't be too crazy to try since it might be .NET still thinking they exist etc (also given that on the other end they sometimes stay as Established).

I'm right now setting up the ping-pong to two of the three, one from a machine totally out of our server park and another on another machine within Azure. This will also give a lot more insight in timings plus eliminate the Azure possible influence. Wiresharking it so far  has been a bit troublesome as there's a lot of traffic, hopefully the clearer ping-pong will show some results here.

**Comment by droyad** [comment]
@janpieterz try adding the `q` and `t` parameters to netstat perhaps

**Comment by janpieterz** [comment]
Will give it a shot on monday, thanks @droyad .

Oddly, since starting the ping pong (got one running to each site) these connection issues have stopped completely. Could be coincidence (something at the ISP changed) so unless it changes I'll stop those first on Monday to see if it starts occurring again.

**Comment by janpieterz** [comment]
Netstat reports similar items and status. Client = halibut client / our servers that somehow start working once fixed

Before any changes:
- 8 established in host connections to client that is unable to connect
- 2 established in host connections to client that is able to connect

Restarting services on both sides:
- 1 established in host connections to client that is able to connect
- 3 established in host connections to client that is unable to connect 

The unable one simply keeps climbing it's amount of connections.
Ping Pong started to fail relatively quickly, even though the rest of the software kept working. Behaviour is also different (open/closeconnections vs keep open and 'ping health'). 

The firewall bit seems most likely, but sadly not something we can do a lot about from here. Will fire off a continuation test (health ping from all kind of machines) next week to ensure it's not something in Azure specific.

**Comment by droyad** [comment]
I'm closing this for now, please re-open if you find anything relevant. We haven't seen this sort of thing in Octopus, so it sounds like a problem with the environment.
