### ISSUE TITLE
Request error, when server returns Interface implementation.

### ISSUE THREAD

**Issue by SlowLogicBoy** [OctopusDeploy/Halibut#42]
Hey, 
Awesome project.

```
An error occurred when sending a request to 'https://localhost:44344/', after the request began: Error resolving type specified in JSON 'Program+ExampleResult, ℛ℘-d0bc25e5-da34-475a-8b08-3768bb4c383f-2'. Path 'Message.result.$type'.
```

It would be nice that Halibut would be able to deserialize unknown types to dynamic or some kind of proxy with dictionary, when client doesn't recognize the type.

Exception example code:
https://gist.github.com/SlowLogicBoy/cad889cc3db28be0e20794c5fae733ef

**Comment by droyad** [comment]
Hi @SlowLogicBoy,

You can control the serialization by setting `MessageExchangeStream.Serializer`. See https://github.com/OctopusDeploy/Halibut/blob/754cd0fefb7a8cbaddf0006dc0242bc9b9423d62/source/Halibut/Transport/Protocol/MessageExchangeStream.cs#L196 for the default implementation.

We just use Newtonsoft Json.net under the hood, so you can customise the deserialization.

In your case, a dictionary or dynamic won't work as they don't satisfy the .NET Type constraint `IExampleResult`.

What you could do though is create an implementation of `IExampleResult` at runtime, using something like http://www.castleproject.org/projects/dynamicproxy/

You would then set a custom `SerilizationBinder` via `serializer.Binder` that generates the implementation on the fly.
