### ISSUE TITLE
Certificate thumbprints should not be case-sensitive

### ISSUE THREAD

**Issue by khellang** [OctopusDeploy/Halibut#605]
### Team

- [X] I've assigned a team label to this issue

### What happened?

Providing a thumbprint with different casing on the client and server-side gives the following exception:

> The server at https://localhost:8080/ presented an unexpected security certificate. We expected the server to present a certificate with the thumbprint 'a7b12a038945afdee39661bcf59cf1600c811122'. Instead, it presented a certificate with a thumbprint of 'A7B12A038945AFDEE39661BCF59CF1600C811122' and subject '<subject>'.

As you can see, the thumbprint is correct, but differs in casing. It expected lowercase, but got uppercase. Certificate thumbprints are a hex-string representation of SHA-based hashes and shouldn't be treated as equal whether they are upper- or lower case.

### Reproduction

Provide a thumbprint with different casing on the client and server-side.

### Workaround

Aligning the thumbprints with the same case fixes the problem.

**Comment by LukeButters** [comment]
Hi thanks for raising an issue :D.

It looks like thumbprints are always upper case hex:
* net48 it generates a thumbprint in [GetCertHashString 4.8](https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/x509certificates/x509certificate.cs,360) which calls [EncodeHexString](https://referencesource.microsoft.com/#mscorlib/system/security/util/hex.cs,27) which looks to return upper case.
* net6 looks to also [return upper case](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs#L364) (switch branches to net6)

The comparison here is between what it received over the stream (which in the error message is upper case) and what was set on the ServiceEndpoint (which in the error message is lower case). A fix could be to always upper case the thumbprint given to the ServiceEndpoint. If that isn't suitable let us know :)
