### ISSUE TITLE
Route is still present but underlying routetable isn't used

### ISSUE THREAD

**Issue by janpieterz** [OctopusDeploy/Halibut#65]
Let me know if you'd like me to remove this.
https://github.com/OctopusDeploy/Halibut/blob/c999038d626a253dbb8fbaadd9e172a7e14b167f/source/Halibut/IHalibutRuntime.cs#L25

**Comment by droyad** [comment]
We'll remove this in the next major

**Comment by janpieterz** [comment]
@droyad 👌
Is there actually an easy way to do this conceptually, without re-implementing the service on an in-between point? 
For example have a lot of workers (*cough* azure functions for example) route the Halibut connection via a central point for all clients/servers to connect through.

**Comment by droyad** [comment]
No, but it is something I want to build at some stage.

**Comment by janpieterz** [comment]
@droyad We might be able to put some effort into this. 
What line are you thinking of going with this? Would be nice to contribute in a way that's useful for everyone.

From our pov it'd be ideal to separate out all the work to create the invocations from the actual routing/client connection handling. This would allow a lot of vertical scaling options (dynamic workers a-la azure functions/lambda functions or even simply scaled VM's etc).

Ideally we'd even get the ability to get clients connecting to localized servers (EU, US, Asia) to improve client connectivity and our workers to connect to a central gateway that routes it to those localized gateways which then routes it to the appropriate client.
