### ISSUE TITLE
Any plans for Microsoft Generic Host support (HostBuilder etc) 

### ISSUE THREAD

**Issue by vincentparrett** [OctopusDeploy/Halibut#69]
It would be nice to do something like this 

````c#
 var host = new HostBuilder()
        .UseHalibut(options => 
         { 
            options.Port = 9999;
            options.Certificate = @"c:\mycert.pfx";
         })
        .Build();
````
Obviously it would need to be a separate nuget package as it's a .net core 2.2+ thing. I'm happy to have a crack at it, as I'm about to use Halibut in an app that uses the generic host and want to keep my startup code nice an neat!

**Comment by vincentparrett** [comment]
I have made some progress on this, happy to submit a PR (It depends on my pr #71 ). Still some work to do and testing but it compile ;)

So to configure Halibut with the generic host, you would do this 

````c#
        static void Main(string[] args)
        {
            Log.Logger = new LoggerConfiguration()
                .WriteTo.Console()
                .MinimumLevel.Debug()
                .CreateLogger();

            var host = new HostBuilder()
                .UseHalibut((options, services) =>
                {
                    services.RegisterHalibutService<ICalculatorService, CalculatorService>();

                    options.Mode = HalibutServerMode.Listening;
                    options.CertificateFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "HalibutServer.pfx");

                    //Listening
                    options.Listen.EndPoint = new IPEndPoint(IPAddress.IPv6Any, 8433);
                    options.Trust.Add("911B7F9E102486C4E1B299FA8D528FE30F129158");
                    //Polling
                    //options.Polling.BaseUri = "https://localhost:8433";
                    //options.Polling.Subscription = "SQ-TENTAPOLL";
                    //options.Polling.RemoteThumbPrint = "ABC.....";
                    //WS Polling
                    //options.Polling.BaseUri = "wss://localhost:8433/Halibut";
                    //options.Polling.Subscription = "SQ-TENTAPOLL";
                    //options.Polling.RemoteThumbPrint = "ABC..";

                    //proxy
                    //options.ProxyDetails = new ProxyDetails("myproxy", 9433, Transport.Proxy.ProxyType.HTTP);
                })
                .UseConsoleLifetime()
                .Build();

            Console.WriteLine("Servier is running, Ctrl+C to stop");
            host.RunAsync();          
        }
````

Of course in a real application you would do more here, but the halibut config is simple and neat.

**Comment by vincentparrett** [comment]
I have pushed a working version to [my fork](https://github.com/VSoftTechnologies/Halibut/tree/f-generic-host-extensions) - comments welcome.

**Comment by vincentparrett** [comment]
I grew impatient (need to get on with migrating from wcf to halibut) so I created a [separate project ](https://github.com/VSoftTechnologies/Halibut.Hosting) for it, not quite as neat without the ITrustProvider PR but will work all the same. I haven't published a nuget package just yet (will wait to see a response here).

**Comment by johnsimons** [comment]
This is awesome

I was also thinking of using the ASP.NET core pipeline to manage the WebSockets, so in essence, remove the transport from Halibut, and that is handled by eg Kestrel ( https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2#how-to-use-websockets )

**Comment by vincentparrett** [comment]
Thanks. I really does keep everything nice and neat and it made it absolutely trivial for us to replace wcf with halibut (I won't miss wcf!).  We're using halibut for coms between the build server and the build agents (Continua CI). We're migrating from .net 4.7.2 to .net core 3.0 and I was dreading the wcf change but in the end it turned out to be pretty simple (migrating mvc though is death by a thousand cuts!). 

So should I submit a PR for this?

**Comment by johnsimons** [comment]
Well given this is a completely new project, is there really a need to include it in this repo?

**Comment by vincentparrett** [comment]
Up to you guys, but it seems like everything is going this way now so it would make sense for it to be part of the halibut repo. It is pretty small, but does need to be a separate nuget package due to it's dependencies differing from halibut (Microsoft.Extensions.Hosting which halibut itself doesn't need).  

It really should be named Halibut.Extensions.Hosting but I didn't do that in case you decided to create your own package.

**Comment by vincentparrett** [comment]
Seems like there are two conventions for the package names 
[https://www.nuget.org/packages?q=Extensions.Hosting](https://www.nuget.org/packages?q=Extensions.Hosting)

Company.Extensions.Hosting.Product 
or 
Extensions.Hosting.Product

**Comment by vincentparrett** [comment]
I renamed the package  
[VSoft.Extensions.Hosting.Halibut](https://github.com/VSoftTechnologies/VSoft.Extensions.Hosting.Halibut)

I would welcome any feedback on this, will probably publish on nuget in the next few days.

**Comment by vincentparrett** [comment]
Published to nuget
[https://www.nuget.org/packages/VSoft.Extensions.Hosting.Halibut/](https://www.nuget.org/packages/VSoft.Extensions.Hosting.Halibut/)

I'll close this now since it's done.
